### ISSUE TITLE
ESX and Synology

### ISSUE THREAD

**Issue by Drealine** [rgc2000/NutClient-ESXi#2]
Hi René
I'm French but keep english for all users.
Synology can make an UPS Server but we can't add user and password, just with IP address source.
It's possible to implement a variable to bypass this ?

I can't leave blank user/password, the service not start.

Tk a lot!

**Comment by My-Random-Thoughts** [comment]
The Synology details should be:

`UserVars.NutUser = monuser`
`UserVars.NutPassword = secret`
`UserVars.NutUpsName = ups@{syno-ip-address}`

EDIT TO ADD:
You can get the username/password values from the file `/etc/ups/upsd.users`:

    # MONITOR myups@localhost 1 upsmon pass master (or slave)
    [monuser]
        password = secret
        upsmon master

The username is the one in square brackets [ ]
The password is as listed

**Comment by Drealine** [comment]
Hi @My-Random-Thoughts 
I'm already using it but when Synology update DSM, the conf file is reset.
I use Home Assistant with UPS integration and can be authenticate without user/pw, so maybe it's possible to implement it ?

Tk

**Comment by My-Random-Thoughts** [comment]
You have two options then:

1. Keep changing the Synology UN/PW every time you do an update
2. Use the given Synology UN/PW in all you do, including Home Assistant

You could plug the UPS data cable somewhere else and use the Synology in slave mode, but then you will still need to use the username/password that the Synology expects.

**Comment by Drealine** [comment]
Hm, the conf file seems not be understand by Syno.
I look in another forums and seems to be not readable by DSM since DSM7.0 :( 
So I think, I've to setup an UPS server and use Syno as an esclave.

**Comment by My-Random-Thoughts** [comment]
>  So I think, I've to setup an UPS server and use Syno as an esclave.

The issue with that, is that the Synology expects to only be a slave to another Synology, so the UN/PW issue may still arise.

**Comment by rgc2000** [comment]
Hi, @My-Random-Thoughts may be right. Configuring at least one user and a password is mandatory in NUT server. Otherwise it would be useless. So, even if the admin web interface does not allow you to change it there are probably default user/password that are set in the server upsd.users file. I have no Synology NAS and I can't help you more than using google to find the answer.

**Comment by Drealine** [comment]
Ok I found in the conf file of upsd.users that a default user is created by syno :

User : monuser
Password : secret

So I set credentials and it's ok :)
@rgc2000 if you want, you can add this in your website

Tk

**Comment by My-Random-Thoughts** [comment]
> Ok I found in the conf file of upsd.users that a default user is created by syno :
> 
> User : monuser Password : secret

That's what I said at the beginning  :)

**Comment by Drealine** [comment]
Oh sorry @My-Random-Thoughts , I didn't see your EDIT!
