### ISSUE TITLE
upsc测试提示`GLIBC_2.16' not found

### ISSUE THREAD

**Issue by jameslan520** [rgc2000/NutClient-ESXi#7]
/opt/nut/bin/upsc upshost@192.168.x.x
./upsc: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /opt/nut/lib/libupsclient.so.6)
./upsc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/nut/lib/libupsclient.so.6)

**Comment by rgc2000** [comment]
You should investigate a bit before posting such a trivial error message with no explanations at all on your context.

This means that you are using an unsupported developpement environnement to build the package. The generated binaries do not comply with your ESXi requirements.

This is what I can say depending on development linux used :

- CentOS 6 : ok for ESXi targets from 5.0 to 8.0
- CentOS 7 : ok for ESXi targets from 6.7 to 8.0 (recommended unless you are using a very old ESXi version)
- Rocky 8 : ok for ESXi targets from 8.0

ESXi 8 requires the binaries to be 64-bit. 32-bit binaries can run on ESXi up to version 7.0

Personally I use an old CentOS 6.10 x86_64 to provide the binary package running on all ESXi versions from 5.0
For other linux distributions, I don't know and I will not search.

**Comment by rgc2000** [comment]
Not a code issue
