### ISSUE TITLE
2.4.1 Last Release I Can Install -  Missing .tar.gz for Future Releases

### ISSUE THREAD

**Issue by war59312** [rgc2000/NutClient-ESXi#8]
Hi,

First off, thank you so much for this.

Looks like Release 2.4.1 is the last build you included the .tar.gz for.

I am assuming you meant to include the .tar.gz for these releases too?

[2.5.0](https://github.com/rgc2000/NutClient-ESXi/releases/tag/2.5.0)
[2.6.0](https://github.com/rgc2000/NutClient-ESXi/releases/tag/2.6.0)
[2.6.1](https://github.com/rgc2000/NutClient-ESXi/releases/tag/2.6.1)
[2.6.2](https://github.com/rgc2000/NutClient-ESXi/releases/tag/2.6.2)

I tried to install 2.6.2 and 2.6.1 offline_bundle.zip verion but it fails:

```
[will@esxi:~] esxcli software vib install -d NutClient-ESXi-2.8.1-2.6.1-offline_bundle.zip
 [MetadataDownloadError]
 Could not download from depot at zip:/var/log/vmware/NutClient-ESXi-2.8.1-2.6.1-offline_bundle.zip?index.xml, skipping (('zip:/var/log/vmware/NutClient-ESXi-2.8.1-2.6.1-offline_bundle.zip?index.xml', '', "Error extracting index.xml from /var/log/vmware/NutClient-ESXi-2.8.1-2.6.1-offline_bundle.zip: [Errno 2] No such file or directory: '/var/log/vmware/NutClient-ESXi-2.8.1-2.6.1-offline_bundle.zip'"))
        url = zip:/var/log/vmware/NutClient-ESXi-2.8.1-2.6.1-offline_bundle.zip?index.xml
 Please refer to the log file for more details.

```

This is on ESXi 8.0 Update 2b.

2.4.1 NutClient-ESXi-2.8.0-2.4.1.x86_64.tar.gz release installed fine:

```
[will@esxi:~] ./upsmon-install.sh
Installation Result
   Message: Operation finished successfully.
   VIBs Installed: Margar_bootbank_upsmon_2.8.0-2.4.1
   VIBs Removed:
   VIBs Skipped:
   Reboot Required: false
   DPU Results:
```

Best,

Will

**Comment by rgc2000** [comment]
Hi, I stopped to provide the tar.gz file here in GitHub releases. The offline depot file is a much better way to install the package and works with every ESXi supported version. The tar.gz file is still available in the web article in my blog. When you call the esxcli install command you have to provide the full path to the offline depot file.

**Comment by war59312** [comment]
Got it, thanks.

```
[will@esxi:~] esxcli software vib install -d /NutClient-ESXi-2.8.2-2.6.2-offline_bundle.zip
Installation Result
   Message: Operation finished successfully.
   VIBs Installed: Margar_bootbank_upsmon_2.8.2-2.6.2
   VIBs Removed: Margar_bootbank_upsmon_2.8.0-2.4.1
   VIBs Skipped:
   Reboot Required: false
   DPU Results:
```

BTW East way for user to grab the file:

`wget --no-check-certificate https://github.com/rgc2000/NutClient-ESXi/releases/download/2.6.2/NutClient-ESXi-2.8.2-2.6.2-offline_bundle.zip`

**Comment by rgc2000** [comment]
Using full path for bundle to instal is mandatory for esxcli install
The tar.gz version of the installation process is only needed for ESXi 5.x. Please use the offline_bundle for newer ESXi
